[package]
name = "ontheflywallet"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "otfwallet"
path = "bin/main.rs"

[dependencies]
clap = { version = "4.5.53", features = ["derive"] }
eyre = "0.6.12"
rustyline = "17.0.2"
yansi = "1.0.1"
